# Generated by Django 4.2.7 on 2023-12-19 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0001_initial'),
        ('categories', '0001_initial'),
        ('books', '0002_alter_books_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='author_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authors.authors'),
        ),
        migrations.AlterField(
            model_name='books',
            name='category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.categories'),
        ),
    ]
